import { createFileRoute } from "@tanstack/react-router";
import { SeoLandingPage, seoHead } from "@/lib/seo-pages";

const config = {"path": "/invoice-software-for-small-business", "title": "Invoice Software for Small Businesses | Honest Invoice", "description": "Invoice and estimate software for small service businesses. Create professional invoices faster with AI, collect payments online, and manage recurring billing.", "h1": "Invoice software for small service businesses", "eyebrow": "Small business invoicing", "intro": "Give a small team a faster way to quote work, create invoices, and collect payments. Honest Invoice keeps the billing workflow simple while AI handles repetitive line-item work.", "workflow": "A faster billing workflow for a growing business", "audience": "A fit for small service companies that need professional billing without adopting a large accounting or field-service suite.", "examples": ["Home-service jobs with labor and material breakdowns", "Agency projects with retainers and one-off services", "Cleaning contracts with recurring visits", "Bookkeeping and professional services billed monthly"], "benefits": ["Create estimates and invoices from a consistent workflow", "AI-assisted line items reduce repetitive data entry", "Client payment links can speed up collection", "Saved clients and rates keep future invoices consistent", "Plans scale from a free starting point to paid business features"], "faq": [{"q": 'Who is Honest Invoice for?', "a": 'Honest Invoice is built for contractors, freelancers, and service businesses that need a focused invoicing workflow.'}, {"q": 'Can a small business customize invoices?', "a": 'Yes. Pro and Business plans include branding controls such as logos and colors.'}, {"q": 'Does Honest Invoice replace full accounting software?', "a": 'No. It is intentionally focused on invoicing, estimating, client billing, and related workflows.'}]};

export const Route = createFileRoute("/invoice-software-for-small-business")({
  head: () => seoHead(config),
  component: () => <SeoLandingPage config={config} />,
});
