import { createFileRoute } from "@tanstack/react-router";
import { SeoLandingPage, seoHead } from "@/lib/seo-pages";

const config = {"path": "/invoice-software-for-freelancers", "title": "Invoice Software for Freelancers | Honest Invoice", "description": "Simple invoice software for freelancers and independent professionals. Create estimates, branded invoices, payment links, and recurring invoices with AI assistance.", "h1": "Simple invoice software for freelancers", "eyebrow": "Freelancer invoicing", "intro": "Create polished invoices without spending your best working hours on admin. Describe the project, let AI draft the details, review them, and send.", "workflow": "Turn project notes into an invoice", "audience": "Useful for designers, developers, consultants, photographers, writers, marketers, and other independent professionals.", "examples": ["Website project with milestones and development hours", "Consulting engagement with hourly services and expenses", "Photography session with packages, editing, and travel", "Monthly marketing retainer with recurring billing"], "benefits": ["Plain-English job or project descriptions become draft line items", "Branded invoices that look professional for client work", "Estimates before work begins and invoices after approval", "Recurring billing for retainers and ongoing services", "Free plan available for getting started"], "faq": [{"q": 'Does Honest Invoice work for solo freelancers?', "a": 'Yes. It is designed for freelancers, independent professionals, and small service businesses.'}, {"q": 'Can I invoice recurring clients?', "a": 'Yes. Recurring invoices are supported on eligible plans.'}, {"q": 'Does Honest Invoice replace accounting software?', "a": 'No. Honest Invoice focuses on estimates, invoices, client billing, and related workflows rather than trying to replace every accounting function.'}]};

export const Route = createFileRoute("/invoice-software-for-freelancers")({
  head: () => seoHead(config),
  component: () => <SeoLandingPage config={config} />,
});
