import { createFileRoute } from "@tanstack/react-router";
import { SeoLandingPage, seoHead } from "@/lib/seo-pages";

const config = {"path": "/invoice-software/plumbers", "title": "Plumber invoice software | Honest Invoice", "description": "Plumber invoice software for repairs, installations, service calls, and maintenance. Draft labor and material line items from a plain-English job description.", "h1": "Turn plumbing job notes into a professional invoice.", "eyebrow": "Plumbers invoicing", "intro": "Plumber invoice software for repairs, installations, service calls, and maintenance. Draft labor and material line items from a plain-English job description. Honest Invoice keeps the workflow focused: describe the work, review the AI-generated line items, and send the invoice.", "workflow": "From the service call to a clear invoice", "audience": "Built for plumbers who need fast estimates and invoices while they are in the field or moving between jobs.", "examples": ["repaired leaking water heater, replaced shutoff valve, 2.5 hours labor", "Leak repairs with labor and materials", "Estimate a new job before work starts and convert it into an invoice", "Recurring service billing for repeat customers"], "benefits": ["AI-assisted labor and material line items from plain-English job notes", "Professional estimates and invoices for client-facing work", "Payment links through Stripe on eligible plans", "Client and rate information can be reused on future documents", "Works from a mobile-first web workflow"], "faq": [{"q": 'Can plumbers use Honest Invoice for estimates?', "a": 'Yes. Honest Invoice supports estimates so you can quote plumbers work before creating the final invoice.'}, {"q": 'Can I describe a job instead of entering every line item?', "a": 'Yes. The AI workflow can draft labor and material line items from a plain-English description. Review the result before sending.'}, {"q": 'Is there a free plan?', "a": 'Yes. The Free plan supports up to 5 invoices per month with no credit card required.'}]};

export const Route = createFileRoute("/invoice-software/plumbers")({
  head: () => seoHead(config),
  component: () => <SeoLandingPage config={config} />,
});
